apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: postgres 
spec:
  selector:
    matchLabels:
      app: postgress
  replicas: 3
  serviceName: postgress 
  template:
    metadata:
      labels:
        app: postgress 
    spec: 
      initContainers:
        - name: postges-init 
          image: postgres
          command: #inside the pod all the host name of the pod will be in ordinal number postgress-1 
          - bash 
          - "-c"
          - | 
             set -ex
             [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
             ordinal=${BASH_REMATCH[1]}
             if [[ $ordinal -eq 0 ]]; then
               printf "I am the primary"
             else
              printf "I am a read-only replica"
             fi
      containers: 
        - name: postgres 
          image: postgres 
          env: 
            - name: POSTGRES_USER
              value: postgres 
            - name: POSTGRES_PASSWORD
              value: postgres 
            - name: POD_IP 
              valueFrom:
                fieldRef: 
                  apiVersion: v1 
                  fieldPath: status.podIP
          ports: 
            - name: postgres 
              containerPort: 5432 
  volumeClaimTemplates:
      - metadata: 
          name: data 
        spec:
          storageClassName: "local-path" 
          accessModes: ["ReadWriteOnce"]
          resources: 
            requests: 
              storage: 1Gi
             



